---
- hosts: webservers
  become: yes
  vars:
    db_host: 172.28.10.16
    db_name: spesa_db
    db_user: user_spesa
    db_pass: PasswordSegreta123

  tasks:
    - name: import EPEL GPG key
      rpm_key:
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
        state: present

    - name: install nginx, php and tools
      yum:
        name:
          - nginx
          - php
          - php-mysqlnd
          - php-fpm
          - libselinux-python
        state: latest

    - name: Set SELinux to Permissive
      selinux:
        policy: targeted
        state: permissive

    - name: Stop Firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Configure PHP-FPM to listen on TCP
      lineinfile:
        path: /etc/php-fpm.d/www.conf
        regexp: '^listen = '
        line: 'listen = 127.0.0.1:9000'
      notify: Restart PHP

    - name: Remove default index.html
      file:
        path: /usr/share/nginx/html/index.html
        state: absent

    - name: Deploy PHP application
      copy:
        dest: /usr/share/nginx/html/index.php
        content: |
          <?php
          $conn = new mysqli("{{ db_host }}", "{{ db_user }}", "{{ db_pass }}", "{{ db_name }}");
          if ($conn->connect_error) { die("Errore DB: " . $conn->connect_error); }
          $result = $conn->query("SELECT item FROM spesa");
          echo "<h1>Lista Spesa</h1><h3>Server Web: " . gethostname() . "</h3><ul>";
          while($row = $result->fetch_assoc()) { echo "<li>" . $row["item"] . "</li>"; }
          echo "</ul>";
          ?>

    - name: Fix permissions for Web Root
      file:
        path: /usr/share/nginx/html
        state: directory
        owner: nginx
        group: nginx
        recurse: yes

    - name: Overwrite Nginx Configuration
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          user nginx;
          worker_processes auto;
          error_log /var/log/nginx/error.log;
          pid /run/nginx.pid;
          include /usr/share/nginx/modules/*.conf;

          events {
              worker_connections 1024;
          }

          http {
              log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for"';

              access_log  /var/log/nginx/access.log  main;
              sendfile            on;
              tcp_nopush          on;
              tcp_nodelay         on;
              keepalive_timeout   65;
              types_hash_max_size 2048;
              include             /etc/nginx/mime.types;
              default_type        application/octet-stream;

              server {
                  listen       80 default_server;
                  listen       [::]:80 default_server;
                  server_name  _;
                  root         /usr/share/nginx/html;
                  index        index.php index.html;

                  location ~ \.php$ {
                      fastcgi_pass   127.0.0.1:9000;
                      fastcgi_index  index.php;
                      fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                      include        fastcgi_params;
                  }

                  location / {
                  }
              }
          }
      notify: Restart Nginx

    - name: enable and start services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - nginx
        - php-fpm

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
    - name: Restart PHP
      service:
        name: php-fpm
        state: restarted
